export enum ActionType {
  // Auth
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // User
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_ACTIVATE = 'USER_ACTIVATE',
  USER_PASSWORD_RESET = 'USER_PASSWORD_RESET',
  USER_FORCE_LOGOUT = 'USER_FORCE_LOGOUT',

  // Product
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',

  // Warehouse
  WAREHOUSE_CREATE = 'WAREHOUSE_CREATE',
  WAREHOUSE_UPDATE = 'WAREHOUSE_UPDATE',
  WAREHOUSE_DELETE = 'WAREHOUSE_DELETE',

  // Stock
  STOCK_ADD = 'STOCK_ADD',
  STOCK_ASSIGN = 'STOCK_ASSIGN',
  STOCK_ADJUST = 'STOCK_ADJUST',

  // Sales
  SALE_CREATE = 'SALE_CREATE',
  SALE_CANCEL = 'SALE_CANCEL',
}
