export enum ActionType {
  // Auth
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // User
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_ACTIVATE = 'USER_ACTIVATE',
  USER_PASSWORD_RESET = 'USER_PASSWORD_RESET',
  USER_FORCE_LOGOUT = 'USER_FORCE_LOGOUT',

  // Product
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',

  // Warehouse
  WAREHOUSE_CREATE = 'WAREHOUSE_CREATE',
  WAREHOUSE_UPDATE = 'WAREHOUSE_UPDATE',
  WAREHOUSE_DELETE = 'WAREHOUSE_DELETE',

  // Stock
  STOCK_ADD = 'STOCK_ADD',
  STOCK_ASSIGN = 'STOCK_ASSIGN',
  STOCK_ADJUST = 'STOCK_ADJUST',

  // Sales
  SALE_CREATE = 'SALE_CREATE',
  SALE_CANCEL = 'SALE_CANCEL',
  SALE_APPROVE = 'SALE_APPROVE',
  SALE_REJECT = 'SALE_REJECT',
  SALE_ASSIGN = 'SALE_ASSIGN',

  // Warehouse Users
  WAREHOUSE_USER_ASSIGN = 'WAREHOUSE_USER_ASSIGN',
  WAREHOUSE_USER_REMOVE = 'WAREHOUSE_USER_REMOVE',

  // Store
  STORE_CREATE = 'STORE_CREATE',
  STORE_UPDATE = 'STORE_UPDATE',
  STORE_DELETE = 'STORE_DELETE',

  // Sales Targets
  SALES_TARGET_CREATE = 'SALES_TARGET_CREATE',
  SALES_TARGET_UPDATE = 'SALES_TARGET_UPDATE',
  SALES_TARGET_DELETE = 'SALES_TARGET_DELETE',
}
